{% set name = "jsonref" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68b330c6815dc0d490dbb3d65ccda265ddde9f7856fd2f3322f971d456ea7549

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - jsonref

about:
  home: http://github.com/gazpachoking/jsonref
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of JSON Reference for Python

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
