{% set name = "jsonref" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51d3e18b83ca7170ff51286a0e1a6719d8b7fcc7abdb16b189395a8536996b97

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - jsonref

about:
  home: http://github.com/gazpachoking/jsonref
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of JSON Reference for Python

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
